---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by caohua.
--- DateTime: 2020/12/10 13:54
---

ShopCtrl = {};
local this = ShopCtrl;

local message;
local transform;
local gameObject;

--构建函数--
function ShopCtrl.New()
    logWarn("ShopCtrl.New--->>");
    return this;
end

function ShopCtrl.Awake()
    logWarn("ShopCtrl.Awake--->>");
    panelMgr:CreatePanel('Shop', this.OnCreate);
end
function ShopCtrl.OnCreate(obj)
    log("创建1");
    gameObject = obj;
    transform = obj.transform;
    message = gameObject:GetComponent('CustomBehaviour');
    log("创建");
end

--单击事件--
function ShopCtrl.OnClick(go)
    destroy(gameObject);
end

--关闭事件--
function ShopCtrl.Close()
    panelMgr:ClosePanel(CtrlNames.message);
end