---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by caohua.
--- DateTime: 2020/12/10 19:43
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by caohua.
--- DateTime: 2020/12/10 13:50
---
local transform;
local gameObject;

LoginPanel = {};
local this = LoginPanel;

--启动事件--
function LoginPanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;
    --log("11111111111111111111111111111111111111"..transform.name );

    this.InitPanel();
    logWarn("Awake lua--->>"..gameObject.name);
end

--初始化面板--
function LoginPanel.InitPanel()
    --log("222222222222222222222222");
    --log(gameObject.name);
    --this.btnClose = transform:Find("LoginPanel").gameObject;
    --log("3333333333333333333333333");
    LoginPanel.accountInput = transform:Find("AccountInput").gameObject;
    LoginPanel.passwordInput = transform:Find("PasswordInput").gameObject;
    LoginPanel.loginButton = transform:Find("LoginButton").gameObject;
    --asd = LoginPanel.loginButton:GetComponent("Button");
    --log("11111111111111111111111111111"..LoginPanel.loginButton);
    LoginPanel.remberPassword = transform:Find("RemberPassword").gameObject;
    --LoginPanel.TestDotween1();
    --LoginPanel.TestDotween2();
end

function LoginPanel.TestDotween1()
    local originPos = LoginPanel.loginButton.transform.localPosition;
    local targetPos = Vector3(originPos.x-100,originPos.y,0);
    LoginPanel.loginButton.transform:DOLocalMove(targetPos,0.5):SetLoops(-1,DG.Tweening.LoopType.Yoyo)
            :OnComplete(function()
                 log("Dotween anim Complete")
             end);
end
function LoginPanel.TestDotween2()
    local originPos = LoginPanel.loginButton.transform.localPosition;
    local targetPos = Vector3(originPos.x,originPos.y-100,0);
    LoginPanel.loginButton.transform:DOLocalMove(targetPos,0.5):SetLoops(-1,DG.Tweening.LoopType.Yoyo)
              :OnComplete(function()
        log("Dotween anim Complete")
    end);
end


--单击事件--
function LoginPanel.OnDestroy()
    logWarn("OnDestroy---->>>");
end

