---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by caohua.
--- DateTime: 2020/12/27 15:31
---
Mytemp =
{
    --里面可以放一些属性
    Hp = 100,
    att = 50,
    name = "good tank",
}

function Mytemp:Awake()
    --print("TankCmp Awake name = "..self.name );
end

function Mytemp:Start()
    --print("TankCmp Start name = "..self.name );
end

function Mytemp:Update()
    --print("TankCmp Update name = "..self.name );
end

--创建对象
function Mytemp:New(obj)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    return o
end