---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by caohua.
--- DateTime: 2020/12/15 15:41
---
function fib(n)
    local a, b = 0, 1
    while n > 0 do
        a, b = b, a + b
        n = n - 1
    end

    return a
end

function CouFunc()
    print("helloworldCouStart");
    print("当前帧数为：".. Time.frameCount);

    for  i = 1, 5 do
        print("当前帧数为：".. Time.frameCount);
        coroutine.wait(1);
    end
    print("helloworldCouStart");
    print("当前帧数为：".. Time.frameCount);
end
function TestCortinue()
    coroutine.start(CouFunc)
end
local delay = nil;
function Delay()
    local c = 1

    while true do
        coroutine.wait(1)
        print("Count: "..c)
        c = c + 1
    end
end
function StartDelay()
    delay = coroutine.start(Delay)
end
function StartDelay()
    coroutine.stop(delay)
end


-----------------------------------
function DoClick1(go)
    print('click1 gameObject is111 '..go.name)
end

function DoClick2(go)
    print('click2 gameObject is222 '..go.name)
end
function MyPClick1(go)
    print('click222 yWUYFdufgDF name:'..go.name);
end
function MyPClick2(go)
    print('click222 yWUYFdufgDF name:'..go.name);
end
function AddClick1(listener)
    if listener.onClick then
        print('Addlistener     clll')
        listener.onClick = listener.onClick + DoClick1
    else
        listener.onClick = DoClick1
    end
end
function MyAddClick1(listener)
    if listener.onClick then
        print('MyAddlistener 111111111');
        listener.onClick  = listener.onClick + MyPClick2();
    end
end

function AddClick2(listener)
    if listener.onClick then
        print('Addlistener     c222')
        listener.onClick = listener.onClick + DoClick2
    else
        listener.onClick = DoClick2
    end
end

function SetClick1(listener)
    if listener.onClick then
        listener.onClick:Destroy()
    end
    print( '  ReAddclick     clll')
    listener.onClick = DoClick1
end
function MySetClick1()
    if listener.onClick then
        listener.onClick:Destroy()
    end
    print('set onclick to click1');
    list.onClick = MyPClick1();
end
function RemoveClick1(listener)
    if listener.onClick then
        print('Remove     clll')
        listener.onClick = listener.onClick - DoClick1
    else
        print('empty delegate')
    end
end
function MyRemoveClick1(listener)
    if listener.onClick then
        print('MyRemove     clll')
        listener.onClick = listener.onClick - DoClick1
    else
        print('empty delegate')
    end
end

function RemoveClick2(listener)
    if listener.onClick then
        print('Remove     c222')
        listener.onClick = listener.onClick - DoClick2
    else
        print('empty delegate')
    end
end

--测试重载问题
function TestOverride(listener)
    listener:SetOnFinished(TestEventListener.OnClick(DoClick1))
    listener:SetOnFinished(TestEventListener.VoidDelegate(DoClick2))
end

function TestEvent()
    print('this is a event')
end
function MyTestEvent()
    print('this is a event')
end
function AddEvent(listener)

    listener.onClickEvent = listener.onClickEvent + TestEvent
end
function MyAddEvent(listener)

    listener.onClickEvent = listener.onClickEvent + MyTestEvent
end
function RemoveEvent(listener)
    listener.onClickEvent = listener.onClickEvent - TestEvent
end
function MyRemoveEvent(listener)
    listener.onClickEvent = listener.onClickEvent - MyTestEvent
end
local t = {name = 'byself'}

function t:TestSelffunc()
    print('callback with self: '..self.name)
end
local My = {name = 'Mynameis'}

function My:MyTestSelffunc()
    print('callback with delf: '..self.name)
end
function AddSelfClick(listener)
    if listener.onClick then
        listener.onClick = listener.onClick + TestEventListener.OnClick(t.TestSelffunc, t)
    else
        listener.onClick = TestEventListener.OnClick(t.TestSelffunc, t)
    end
end
function MyAddSelfClick(listener)
    if listener.onclick then
        listener.onclick = listener.onclick + TestEventListener.OnClick(My.MyTestSelffunc,My)
    end
end

function RemoveSelfClick(listener)
    if listener.onClick then
        listener.onClick = listener.onClick - TestEventListener.OnClick(t.TestSelffunc, t)
    else
        print('empty delegate')
    end
end
function MyRemoveSelfClick(listener)
    if listener.onClick then
        listener.onClick = listener.onClick - TestEventListener.OnClick(My.MyTestSelffunc, My)
    else
        print('empty delegate')
    end
end